export async function getProTable1Data() {
  // Fake delay
  await new Promise((resolve) => setTimeout(resolve, 1500));

  return [
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
    {
      eventNo: "1",
      eventsubNo: "1A",
      distance: "100",
      stroke: "FreeStyle",
      fee:"8",
      age:"10",
      timeup: "NT",
      course:"S",
    },
  ];
}

